version: "3"
services:
  db:
    container_name: 'db'
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - custom
networks:
  custom:
    driver: bridge
volumes:
  pg_data: Null