"""booking_table_added

Revision ID: d731bd1096a8
Revises: ea096d14a1f9
Create Date: 2023-01-17 13:48:01.214929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd731bd1096a8'
down_revision = 'ea096d14a1f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
