"""booking_table_added

Revision ID: e8f2ce371fd1
Revises: d731bd1096a8
Create Date: 2023-01-17 13:51:25.480227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f2ce371fd1'
down_revision = 'd731bd1096a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'booking_time', ['available_time_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking_time', type_='unique')
    # ### end Alembic commands ###
