"""booking_table_added

Revision ID: ea096d14a1f9
Revises: ecfbeb109068
Create Date: 2023-01-17 12:52:24.266794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea096d14a1f9'
down_revision = 'ecfbeb109068'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_time',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('available_time_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['available_time_id'], ['available_time.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_time')
    # ### end Alembic commands ###
